common:
  hostname: test.com

application:
  port: 4000

service:
  enabled: true
  prometheusMonitoring: true
  backendTarget: ps2alerts-microservice-pc # This points to a particular index in deployments

ingress:
  enabled: true
  wwwRedirect: true
  annotations: |
    nginx.ingress.kubernetes.io/server-snippet: |
          expires 1d;
          add_header Cache-Control "public, must-revalidate";

deployments:
  one:
    index: pc
    enabled: true
    containerImage: dockerhub.com/foo
    probes:
      startupProbe:
        enabled: true
        type: command
        command:
          - /bin/bash
          - -c
          - cat /app/ready.file | grep -i "ready"
      readinessProbe:
        enabled: true
        type: httpGet
        httpGetPath: /one
      livenessProbe:
        enabled: true
        type: command
        command:
          - /bin/bash
          - -c
          - ps -ef | grep "run start" | grep -v grep
    env:
      - name: NODE_ENV
        value: production
    nodeSelector:
      nodepool: perm-pool
    scaling:
      enabled: true
      min: 1
      max: 10
      targetCpu: 69
    podDisruptionBudget:
      enabled: true
      minAvailable: 25%
  two:
    index: ps4eu
    enabled: false
    containerImage: dockerhub.com/foo
    probes:
      startupProbe:
        enabled: true
        type: command
        command:
          - /bin/bash
          - -c
          - cat /app/ready.file | grep -i "ready"
      readinessProbe:
        enabled: true
        type: httpGet
        httpGetPath: /two
      livenessProbe:
        enabled: true
        type: command
        command:
          - /bin/bash
          - -c
          - ps -ef | grep "run start" | grep -v grep
    env:
      - name: NODE_ENV
        value: production
  three:
    index: ps4us
    enabled: true
    containerImage: dockerhub.com/foo
    probes:
      startupProbe:
        enabled: true
        type: command
        command:
          - /bin/bash
          - -c
          - cat /app/ready.file | grep -i "ready"
      readinessProbe:
        enabled: true
        type: httpGet
        httpGetPath: /three
      livenessProbe:
        enabled: true
        type: command
        command:
          - /bin/bash
          - -c
          - ps -ef | grep "run start" | grep -v grep
    env:
      - name: NODE_ENV
        value: production
