{{- if eq .Values.service.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.application.port }}
      targetPort: {{ .Values.application.port }}
{{- end }}
