{{- range .Values.deployments }}
  {{- if eq .enabled true }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.common.name }}-{{ .index }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $.Values.common.name }}
spec:
  replicas: {{ .replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ $.Values.common.name }}-{{ .index }}
  template:
    metadata:
      labels:
        app: {{ $.Values.common.name }}-{{ .index }}
        version: {{ $.Values.application.version }}
    spec:
      {{- if .nodeSelector }}
      nodeSelector: {{- .nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: app
          image: {{ .containerImage }}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: {{ .resources.cpu.requests }}
              memory: {{ .resources.mem.requests }}
            limits:
              cpu: {{ .resources.cpu.limits }}
              memory: {{ .resources.mem.limits  }}
          {{- if eq .probes.startupProbe.enabled true }}
          startupProbe:
            {{- if eq .probes.startupProbe.type "command" }}
            exec:
              command: {{- range .probes.startupProbe.command }} {{.}}{{- end }}
            {{- end }}
            {{- if eq .probes.startupProbe.type "httpGet" }}
            httpGet:
              path: {{ .probes.startupProbe.httpGetPath }}
            {{- end }}
            periodSeconds: {{ .probes.startupProbe.periodSeconds }}
            successThreshold: {{ .probes.startupProbe.successThreshold }}
            failureThreshold: {{ .probes.startupProbe.failureThreshold }}
          {{- end }}
          {{- if eq .probes.readinessProbe.enabled true }}
          readinessProbe:
            {{- if eq .probes.readinessProbe.type "command" }}
            exec:
              command: {{- range .probes.readinessProbe.command }} {{.}}{{- end }}
            {{- end }}
            {{- if eq .probes.readinessProbe.type "httpGet" }}
            httpGet:
              path: {{ .probes.readinessProbe.httpGetPath }}
            {{- end }}
            periodSeconds: {{ .probes.readinessProbe.periodSeconds }}
            successThreshold: {{ .probes.readinessProbe.successThreshold }}
            failureThreshold: {{ .probes.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if eq .probes.livenessProbe.enabled true }}
          livenessProbe:
            {{- if eq .probes.livenessProbe.type "command" }}
            exec:
              command: {{- range .probes.livenessProbe.command }} {{.}}{{- end }}
            {{- end }}
            {{- if eq .probes.livenessProbe.type "httpGet" }}
            httpGet:
              path: {{ .probes.livenessProbe.httpGetPath }}
            {{- end }}
            periodSeconds: {{ .probes.livenessProbe.periodSeconds }}
            successThreshold: {{ .probes.livenessProbe.successThreshold }}
            failureThreshold: {{ .probes.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .env }}
          env:
            {{- range .env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
          {{- end }}
    {{- if eq .scaling.enabled true }}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $.Values.common.name }}
  namespace: {{ $.Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $.Values.common.name }}-{{ .index }}
  minReplicas: {{ .scaling.min }}
  maxReplicas: {{ .scaling.max }}
  targetCPUUtilizationPercentage: {{ .scaling.targetCpu }}
    {{- end }}
  {{- end }}
{{- end }}
