{{- if eq .Values.service.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.common.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.common.name }}
    version: {{ .Values.application.version | default .Chart.AppVersion }}
  ports:
    - protocol: TCP
      port: {{ .Values.application.port }}
      targetPort: {{ .Values.application.port }}
  {{- if eq .Values.service.prometheusMonitoring true }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.common.name }}
  namespace: ps2alerts
  labels:
    app: {{ .Values.common.backendTarget }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.common.backendTarget }}
  endpoints:
    - port: "{{ .Values.application.port }}"
  {{- end }}
{{- end }}
