{{- if eq .Values.service.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.common.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.common.name }}
    version: {{ .Chart.AppVersion }}
  ports:
    - protocol: TCP
      port: {{ .Values.application.port }}
      targetPort: {{ .Values.application.port }}
{{- end }}
