# This action bumps the chart version and commits it when deployed to master
name: Build & Deploy Production
on:
  push:
    branches: [master]
jobs:
  bump-version:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Modify version
