# This action bumps the chart version and commits it when deployed to master
name: Update version & release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source code
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 2

      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v41
        with:
          files: |
            charts

      - name: Calculate version
        if: steps.changed-files-specific.outputs.any_modified == 'true'
        id: version
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: charts
        with:
          skip-tag: true
          skip-commit: true
          target-branch: 'master'

      - name: Update Chart.yaml
        if: steps.changed-files-specific.outputs.any_modified == 'true'
        working-directory: charts/microservice
        run: |
          cat <<EOF > Chart.yaml
          apiVersion: v2
          name: ps2alerts-microservice
          version: ${{ steps.version.outputs.newTag }}
          appVersion: ${{ steps.version.outputs.newTag }}
          EOF

      - name: Commit the new Chart.yaml
        if: steps.changed-files-specific.outputs.any_modified == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bumps version to ${{ steps.version.outputs.newTag }}

      - name: Bump version and push tag
        if: steps.changed-files-specific.outputs.any_modified == 'true'
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.version.outputs.newTag }}

      - name: Create new GitHub Release
        if: steps.changed-files-specific.outputs.any_modified == 'true'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.newTag }}
